# Generated by Django 3.1.6 on 2021-02-15 11:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('location', models.CharField(max_length=100)),
                ('oauth2_client_id', models.CharField(max_length=100, unique=True)),
                ('serial_number', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
            ],
        ),
        migrations.CreateModel(
            name='Posse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GatewayTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_flow', models.BooleanField()),
                ('hardware_name', models.CharField(max_length=255)),
                ('unit_name', models.CharField(blank=True, max_length=255)),
                ('unit_type', models.CharField(choices=[('bool', 'Boolean'), ('float', 'Float'), ('int', 'Integer'), ('str', 'String')], max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('dormant', 'Dormant')], default='active', max_length=20)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_sources.gateway')),
            ],
        ),
        migrations.CreateModel(
            name='GatewayStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('data_flow', models.BooleanField()),
                ('os_name', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=255)),
                ('firmware_version', models.CharField(max_length=255)),
                ('maio_edge_version', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_sources.gateway')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddField(
            model_name='gateway',
            name='posse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_sources.posse'),
        ),
        migrations.AddConstraint(
            model_name='gatewaytag',
            constraint=models.UniqueConstraint(fields=('gateway_id', 'label'), name='gateway and label should be unique in GatewayTag.'),
        ),
        migrations.AddConstraint(
            model_name='gatewaytag',
            constraint=models.UniqueConstraint(fields=('gateway_id', 'hardware_name'), name='gateway and hardware_name should be unique in GatewayTag.'),
        ),
        migrations.AddConstraint(
            model_name='gateway',
            constraint=models.UniqueConstraint(fields=('label', 'serial_number'), name='label_serial_number'),
        ),
    ]
