# Generated by Django 2.2.18 on 2021-02-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatewaystatus',
            options={'get_latest_by': 'created_at', 'verbose_name_plural': 'Gateway Status'},
        ),
    ]
