# Generated by Django 2.2.18 on 2021-02-20 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0003_auto_20210220_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaystatus',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_status', to='data_sources.Gateway'),
        ),
    ]
